/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConnectSleeperRouteImport } from './routes/connect-sleeper'
import { Route as LeagueLeagueIdRouteImport } from './routes/league/$leagueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectSleeperRoute = ConnectSleeperRouteImport.update({
  id: '/connect-sleeper',
  path: '/connect-sleeper',
  getParentRoute: () => rootRouteImport,
} as any)
const LeagueLeagueIdRoute = LeagueLeagueIdRouteImport.update({
  id: '/league/$leagueId',
  path: '/league/$leagueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect-sleeper': typeof ConnectSleeperRoute
  '/league/$leagueId': typeof LeagueLeagueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/connect-sleeper' | '/league/$leagueId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/connect-sleeper' | '/league/$leagueId'
  id: '__root__' | '/' | '/connect-sleeper' | '/league/$leagueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectSleeperRoute: typeof ConnectSleeperRoute
  LeagueLeagueIdRoute: typeof LeagueLeagueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect-sleeper': {
      id: '/connect-sleeper'
      path: '/connect-sleeper'
      fullPath: '/connect-sleeper'
      preLoaderRoute: typeof ConnectSleeperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/league/$leagueId': {
      id: '/league/$leagueId'
      path: '/league/$leagueId'
      fullPath: '/league/$leagueId'
      preLoaderRoute: typeof LeagueLeagueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectSleeperRoute: ConnectSleeperRoute,
  LeagueLeagueIdRoute: LeagueLeagueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
